version: '3.3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=opi
      - POSTGRES_USER=opi
      - POSTGRES_PASSWORD=opipostgress
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./
    command: /home/opiapi/opiapi
    volumes:
      - .:/usr/src/app
    ports:
      - "8005:8005"
    depends_on:
      - database
    environment:
      PORT: 8005
      DB_USER: opi
      DB_PASSWORD: opipostgress
      DB_HOST: opiapi_database_1
      DB_NAME: opi
      DB_PORT: 5432
      DB_SSL_MODE: disable

  front:
    build:
      context: ../producto_fullstack/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      REACT_APP_USERNAME: user
      REACT_APP_API_KEY: pass
      REACT_APP_TABLE_NAME:

volumes:
  pgdata: